name: Daily Article Update

on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  update-articles:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Call Update Articles API
        run: |
          echo "Starting article update at $(date)"
          response=$(curl -X GET ${{ secrets.VERCEL_URL }}/api/update-articles --max-time 60)
          if [ $? -eq 0 ]; then
            echo "API Response: $response"
            echo "Update successful"
          else
            echo "API call failed"
            exit 1
          fi
        env:
          VERCEL_URL: ${{ secrets.VERCEL_URL }}

      - name: Log completion
        if: always()
        run: echo "Workflow completed at $(date)"
