name: Daily Article Update

on:
  schedule:
    - cron: '0 22 * * *'  # Runs at 10 PM UTC
  workflow_dispatch:       # Manual trigger
  push:
    branches:
      - main             # Run on push to main

jobs:
  update-articles:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Call Update Articles API
        run: |
          echo "Starting article update at $(date)"
          curl -X GET ${{ secrets.VERCEL_URL }}/api/update-articles
        env:
          VERCEL_URL: ${{ secrets.VERCEL_URL }}

      - name: Log completion
        run: echo "Workflow completed at $(date)"
